module.exports = {
  important: true,
  theme: {
    colors: {
      transparent: "transparent",
      black: "#000",
      white: "#fff",
      gray: {
        1: "#F8F9FA",
        2: "#DDE2E5",
        3: "#ACB5BD",
        4: "#495057"
      },
      primary: {
        default: "#0038FF",
        hover: "#0032E3"
      },
      secondary: {
        default: "#141618",
        hover: "#000"
      },
      error: "#DA1E28",
      success: "#1D833B",
      highlight: "#FFE55E"
    },
    spacing: {
      px: "1px",
      "0": "0",
      "1": "4px",
      "2": "8px",
      "3": "12px",
      "4": "16px",
      "5": "24px",
      "6": "32px",
      "7": "40px",
      "8": "48px",
      "9": "56px",
      "10": "64px"
    },
    borderColor: theme => ({
      ...theme("colors"),
      default: theme("colors.secondary", "currentColor")
    }),
    borderWidth: {
      default: "1px",
      "0": "0",
      "2": "2px"
    },
    width: theme => ({
      auto: "auto",
      ...theme("spacing"),
      "1/2": "50%",
      "1/3": "33.333333%",
      "2/3": "66.666667%",
      "1/4": "25%",
      "2/4": "50%",
      "3/4": "75%",
      "1/5": "20%",
      "2/5": "40%",
      "3/5": "60%",
      "4/5": "80%",
      full: "100%"
    })
  },
  variants: {
    alignItems: [],
    alignSelf: [],
    alignContent: [],
    display: [],
    flexDirection: [],
    flexGrow: [],
    flexShrink: [],
    flexWrap: [],
    height: [],
    inset: [],
    justifyContent: [],
    margin: [],
    padding: [],
    position: [],
    textAlign: [],
    textTransform: [],
    width: [],
    zIndex: []
  },
  corePlugins: {
    container: false,
    cursor: false,
    appearance: false,
    backgroundAttachment: false,
    backgroundColor: false,
    backgroundPosition: false,
    backgroundRepeat: false,
    backgroundSize: false,
    borderCollapse: false,
    borderColor: false,
    borderRadius: false,
    borderStyle: false,
    borderWidth: false,
    boxShadow: false,
    fill: false,
    flex: false,
    float: false,
    fontFamily: false,
    fontSize: false,
    fontSmoothing: false,
    fontStyle: false,
    fontWeight: false,
    letterSpacing: false,
    lineHeight: false,
    listStylePosition: false,
    listStyleType: false,
    maxHeight: false,
    maxWidth: false,
    minHeight: false,
    minWidth: false,
    negativeMargin: false,
    objectFit: false,
    objectPosition: false,
    opacity: false,
    outline: false,
    order: false,
    overflow: false,
    pointerEvents: false,
    resize: false,
    stroke: false,
    tableLayout: false,
    textColor: false,
    textDecoration: false,
    userSelect: false,
    verticalAlign: false,
    visibility: false,
    whitespace: false,
    wordBreak: false
  }
};
